name: ExampleMVVM
options:
  bundleIdPrefix: "com.oleh.kudinov"
configs:
  Debug: debug
  Release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "13.0"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: ""
targets:
  ExampleMVVM:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: ExampleMVVM
        excludes:
          - ExampleMVVM.xcodeproj
    settings:
      INFO_PLIST_FILE: "ExampleMVVM/Resources/Info.plist"
      PRODUCT_BUNDLE_IDENTIFIER: "com.oleh.kudinov.ExampleMVVM"
    resources:
      - ExampleMVVM/Resources

  ExampleMVVMTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - ExampleMVVMTests
    settings:
      INFO_PLIST_FILE: "ExampleMVVMTests/Info.plist"
      PRODUCT_BUNDLE_IDENTIFIER: "com.oleh.kudinov.ExampleMVVMTests"
    dependencies:
      - target: ExampleMVVM

  ExampleMVVMUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - ExampleMVVMUITests
    settings:
      INFO_PLIST_FILE: "ExampleMVVMUITests/Info.plist"
      PRODUCT_BUNDLE_IDENTIFIER: "com.oleh.kudinov.ExampleMVVMUITests"
    dependencies:
      - target: ExampleMVVM

schemes:
  ExampleMVVM:
    shared: true
    build:
      targets:
        ExampleMVVM: all
        ExampleMVVMTests: [test]
        ExampleMVVMUITests: [test]
    test:
      targets:
        - ExampleMVVMTests
        - ExampleMVVMUITests
    run:
      config: Debug
