name: ExampleMVVM
options:
  bundleIdPrefix: "Oleh-Kudinov"
configs:
  Debug: debug
  Release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "13.0"
    SWIFT_VERSION: "5.0"
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: ""
    PROVISIONING_PROFILE_SPECIFIER: ""
    CODE_SIGN_ENTITLEMENTS: ""
packages:
  Common:
    path: Packages/Common
  Domain:
    path: Packages/Domain
  Networking:
    path: Packages/Networking
  Data:
    path: Packages/Data
  Presentation:
    path: Packages/Presentation
targets:
  ExampleMVVM:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: ExampleMVVM
        excludes:
          - ExampleMVVM.xcodeproj
    dependencies:
      - package: Common
      - package: Domain
      - package: Networking
      - package: Data
      - package: Presentation
    settings:
      INFO_PLIST_FILE: "ExampleMVVM/Resources/Info.plist"
      PRODUCT_BUNDLE_IDENTIFIER: "Oleh-Kudinov.ExampleMVVM"
    resources:
      - ExampleMVVM/Resources

  ExampleMVVMTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - ExampleMVVMTests
    dependencies:
      - target: ExampleMVVM
      - package: Common
      - package: Domain
      - package: Networking
      - package: Data
      - package: Presentation
    settings:
      INFO_PLIST_FILE: "ExampleMVVMTests/Info.plist"
      PRODUCT_BUNDLE_IDENTIFIER: "Oleh-Kudinov.ExampleMVVMTests"

  ExampleMVVMUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - ExampleMVVMUITests
    dependencies:
      - target: ExampleMVVM
      - package: Domain
    settings:
      INFO_PLIST_FILE: "ExampleMVVMUITests/Info.plist"
      PRODUCT_BUNDLE_IDENTIFIER: "Oleh-Kudinov.ExampleMVVMUITests"

schemes:
  ExampleMVVM:
    shared: true
    build:
      targets:
        ExampleMVVM: all
        ExampleMVVMTests: [test]
        ExampleMVVMUITests: [test]
    test:
      targets:
        - ExampleMVVMTests
        - ExampleMVVMUITests
    run:
      config: Debug
